stages:
 - build

before_script:
 - gem install bundler
 - bundle install

build_proj:
 stage: build
 script:
  - fastlane beta
 # - xcodebuild clean -project "D&D Beyond Characters.xcodeproj" -scheme "D&D Beyond Characters"
 # - xcodebuild archive -project "D&D Beyond Characters.xcodeproj" -scheme "D&D Beyond Characters"
